### ISSUE TITLE
StyleExtractor input shape

### ISSUE THREAD

**Issue by longxvu** [tcl9876/Diffusion-Handwriting-Generation#5]
In `StyleExtractor` class, the MobileNetV2 model receives an input shape of (96, 96, 3). However, writer image is rarely a square, which leads to the problem of incompatible input shape for `StyleExtractor`.
Here's one example error when running inference with default setting:

```
Input 0 of layer "mobilenetv2_1.00_96" is incompatible with the layer: expected shape=(None, 96, 96, 3), found shape=(96, 96, 1400, 3)
Call arguments received by layer "style_extractor" "f"(type StyleExtractor):
im=tf.Tensor(shape=(96, 96, 1400, 1), dtype=uint8)
im2=None
get_similarity=False
training=False
```

How do we deal with the incompatible shape here? Is it safe to assume that reshaping the writer image to a square doesn't affect the model's performance?

**Comment by tcl9876** [comment]
Hi @longxvu 

Thanks for reaching out. You're right that the writer image shouldn't be square, and it's actually not supposed to reshape the image to a square. 
It's designed for lines where the image is much wider than it is tall, and the style image is allowed to vary in length, since style information is added via a cross-attention like mechanism.

The error you're encountering is because later versions of tensorflow don't like the MobileNet feature extractor being initialized with input_shape (96, 96, 3), since it expects inputs of shape exactly (96, 96, 3).
The simplest solution would be to downgrade tensorflow to 2.3.0. If you want to avoid doing that for some reason, perhaps try replacing "input_shape=(96, 96, 3)" on line 151 of nn.py with "input_shape=(None, None, 3)", although I'm not certain the loaded mobilenet will be the exact same.

Hope this helps,
Troy

**Comment by longxvu** [comment]
Both of your methods work. Thanks for replying
